- name: My First Playbook
  hosts: ansible_target1
  become: yes
  tasks:
  
    - name: Create file using command module
      command: sudo touch /home/ansible_controller/hello.txt

    - name: Replace String
      replace:
        path: /home/app/src/App.js
        regexp: 'Hello World!'
        replace: 'Hello DevOps!'
        backup: yes
        
